"use client";

import { useState } from "react";
import Link from "next/link";
import { SettingsForm, type WatchlistOption } from "@/components/settings/settings-form";
import { SettingsTabBar } from "@/components/settings/settings-tab-bar";
import { Card, CardHeader, CardRow } from "@/components/settings/settings-card";
import { ProfileForm } from "@/components/settings/profile-form";
import { ChangePasswordForm } from "@/components/settings/change-password-form";
import { TwoFactorPanel } from "@/components/settings/two-factor-panel";
import { DangerZone } from "@/components/settings/danger-zone";
import { BillingSettingsPanel } from "@/components/settings/billing-settings-panel";
import { CookiePreferences } from "@/components/settings/cookie-preferences";
import { type SettingsTabId } from "@/lib/settings-categories";
import type { BillingDetail } from "@/lib/actions/billing";
import type { Database } from "@/lib/supabase/types";

type Settings = Database["public"]["Tables"]["user_settings"]["Row"];

interface SettingsTabsProps {
  settings: Settings;
  displayName: string;
  email: string;
  emailVerified: boolean;
  billing: BillingDetail;
  sectorOptions: string[];
  watchlists: WatchlistOption[];
  fx: { effectiveCurrency: string; unavailable: boolean; asOf: string | null };
  intradayAvailable: boolean;
  initialTab: SettingsTabId;
}

const LEGAL_LINKS = [
  { href: "/terms", label: "Terms of Service", blurb: "What Cairn is and is not, including the advice disclaimer." },
  { href: "/privacy", label: "Privacy Policy", blurb: "What Cairn stores, why, and how long it is kept." },
  { href: "/privacy#ai-disclosure", label: "Risk & AI disclosure", blurb: "Nothing Cairn produces is a recommendation to buy, hold, or sell." },
  { href: "/accessibility", label: "Accessibility statement", blurb: "What was tested, what conforms, and the known gaps." },
];

export function SettingsTabs({
  settings,
  displayName,
  email,
  emailVerified,
  billing,
  sectorOptions,
  watchlists,
  fx,
  intradayAvailable,
  initialTab,
}: SettingsTabsProps) {
  const [activeTab, setActiveTab] = useState<SettingsTabId>(initialTab);
  // 2FA is never actually enrolled in this build (no TOTP, no second factor);
  // the badge stays until that ships. See TwoFactorPanel.
  const twoFactorOff = true;

  return (
    <div>
      <SettingsTabBar active={activeTab} onSelect={setActiveTab} twoFactorOff={twoFactorOff} />

      {/* One <Card> per group, 14px gap, matching Cairn Settings.dc.html. */}
      <div className="flex flex-col gap-3.5">
        {activeTab === "account" && (
          <>
            <Card>
              <CardHeader title="Profile" />
              <div className="px-4.5 py-4.5">
                <ProfileForm displayName={displayName} email={email} emailVerified={emailVerified} />
              </div>
              <CardRow label="Password" desc={settings.two_factor_status ? "Change it any time. You stay signed in on this device." : "Change it any time."}>
                <ChangePasswordForm />
              </CardRow>
            </Card>

            <TwoFactorPanel status={settings.two_factor_status ?? "not_enrolled"} />

            <DangerZone />
          </>
        )}

        <SettingsForm
          settings={settings}
          activeTab={activeTab}
          sectorOptions={sectorOptions}
          watchlists={watchlists}
          fx={fx}
          intradayAvailable={intradayAvailable}
        />

        {activeTab === "billing" && <BillingSettingsPanel detail={billing} />}

        {activeTab === "privacy" && (
          <>
            <Card>
              <CardHeader title="AI &amp; your data" note="What Cairn uses AI for, and what leaves your account" />
              <CardRow label="Cairn uses AI to generate analysis and chat content">
                <div className="w-full">
                  <p className="mt-1 max-w-[62ch] text-caption leading-relaxed text-muted text-pretty">
                    Research write-ups, methodology explanations and every assistant reply are produced by a language
                    model. They are not written or reviewed by a human before you see them, and they can be wrong.
                    Probability ranges, confidence levels and sample sizes are computed statistically in code — a
                    Wilson score interval over historical analogs — not generated by the model.
                  </p>
                  <Link href="/privacy#ai-disclosure" className="mt-2 inline-block text-body text-accent hover:underline">
                    Read the full AI disclosure →
                  </Link>
                </div>
              </CardRow>
              <div className="px-4.5 py-4.5">
                <CookiePreferences />
              </div>
              <CardRow label="Export or delete everything" desc="Both live under the Account tab. Deletion follows the process described in the privacy policy — immediate and irreversible.">
                <button
                  type="button"
                  onClick={() => setActiveTab("account")}
                  className="shrink-0 rounded-control border border-line px-3.5 py-2 text-body text-primary transition-colors duration-fast ease-standard hover:border-line-strong"
                >
                  Go to Account →
                </button>
              </CardRow>
            </Card>

            <Card>
              <CardHeader title="Legal" note="Cairn is a research tool, not a broker-dealer" />
              {LEGAL_LINKS.map((l) => (
                <CardRow key={l.href} label={l.label} desc={l.blurb}>
                  <Link
                    href={l.href}
                    className="shrink-0 rounded-control border border-line px-3.5 py-2 text-body text-primary transition-colors duration-fast ease-standard hover:border-line-strong"
                  >
                    Read
                  </Link>
                </CardRow>
              ))}
            </Card>
          </>
        )}
      </div>
    </div>
  );
}
